import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/target/**",
      // next-env.d.ts is auto-generated by Next.js and must not be edited
      "**/next-env.d.ts",
    ],
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  // Guard: the browser-safe barrel (packages/core/src/index.ts) must never
  // import from the node-only subpath. This prevents regressions where a
  // contributor re-adds a node-only export to the default barrel.
  {
    files: ["packages/core/src/index.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["./node", "./node.ts"],
              message:
                "The browser-safe barrel (index.ts) must not import from the node-only subpath (node.ts). Add node-only exports to @nexus/core/node instead.",
            },
          ],
        },
      ],
    },
  },
);
