import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/target/**",
      // next-env.d.ts is auto-generated by Next.js and must not be edited
      "**/next-env.d.ts",
    ],
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  // Guard: the browser-safe barrel (packages/core/src/index.ts) must never
  // import from the node-only subpath. This prevents regressions where a
  // contributor re-adds a node-only export to the default barrel.
  {
    files: ["packages/core/src/index.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["./node", "./node.ts"],
              message:
                "The browser-safe barrel (index.ts) must not import from the node-only subpath (node.ts). Add node-only exports to @nexus/core/node instead.",
            },
          ],
        },
      ],
    },
  },
  // Guard: apps/nextjs is a read-only DB consumer. All writes must route through
  // the agent HTTP API. Banning the full `Db` type and `@nexus/db/client` write
  // surface at the import level gives a compile-time (and lint-time) signal when
  // someone accidentally adds a direct write path.
  //
  // Allowed: `@nexus/db` (for schema tables, helpers like `eq`/`sql`),
  //          `@nexus/db/readonly` (ReadOnlyDb type + asReadOnly helper),
  //          `@nexus/db/schema` (schema-only import).
  // Blocked: `Db` named import from `@nexus/db` or `@nexus/db/client`.
  // Guard: apps/nextjs is a read-only DB consumer outside of lib/db.ts.
  // All writes must route through the agent HTTP API.
  //
  // lib/db.ts is the single DB factory and may import createDb from @nexus/db/client.
  // All other nextjs files must use ReadOnlyDb from @nexus/db/readonly.
  //
  // The rule blocks:
  //   - The full `Db` type from `@nexus/db` or `@nexus/db/client` (outside lib/db.ts)
  //   - Direct `@nexus/db/client` imports outside the DB factory
  {
    files: [
      "apps/nextjs/**/*.ts",
      "apps/nextjs/**/*.tsx",
    ],
    ignores: [
      // lib/db.ts is the DB factory — it legitimately constructs the Db instance.
      "apps/nextjs/src/lib/db.ts",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@nexus/db/client",
              message:
                "apps/nextjs must not import from @nexus/db/client directly (outside lib/db.ts). Use @nexus/db/readonly for typed read access and route all writes through the agent HTTP API.",
            },
          ],
          patterns: [
            {
              group: ["@nexus/db"],
              importNames: ["Db"],
              message:
                "apps/nextjs must not use the full Db type (outside lib/db.ts). Import ReadOnlyDb from @nexus/db/readonly instead. All writes must go through the agent HTTP API.",
            },
          ],
        },
      ],
    },
  },
);
