output "nexus_encryption_key" {
  description = "AES-256 encryption key for nexus session data (generated by Terraform)"
  value       = random_password.nexus_encryption_key.result
  sensitive   = true
}

output "nexus_attach_secret" {
  description = "Shared secret for nexus attach authentication (generated by Terraform)"
  value       = random_password.nexus_attach_secret.result
  sensitive   = true
}

output "postgres_url" {
  description = "PostgreSQL connection URL for nexus-agent (managed by homelab-postgres module)"
  value       = module.homelab_postgres.postgres_url
  sensitive   = true
}

output "homelab_ip" {
  description = "Tailscale IP of the homelab machine"
  value       = var.homelab_ip
}
