//! TTS orchestration - tries ElevenLabs, falls back to system TTS
//!
//! Provides a unified interface for text-to-speech that:
//! 1. Tries ElevenLabs first (if API key available)
//! 2. Falls back to system TTS on failure
//! 3. Returns audio bytes or system TTS result

use super::tts_elevenlabs::ElevenLabsClient;
use super::tts_system::SystemTts;
use tracing::{debug, info, warn};

/// Result of TTS synthesis
#[derive(Debug)]
pub enum TtsResult {
    /// Audio data generated by ElevenLabs (MP3 bytes)
    Audio(Vec<u8>),
    /// System TTS handled the speech (provider name)
    SystemSpoke(String),
}

/// Normalize dev/ops text into natural speech.
///
/// Transforms patterns that sound robotic when read verbatim:
/// - `10/10` → "10 of 10"
/// - `daemon=active` → "daemon active"
/// - `(restarted)` → "restarted"
/// - `OK` → "okay"
fn normalize_for_speech(text: &str) -> String {
    let mut s = text.to_string();

    // Remove markdown formatting
    s = s.replace("**", "");
    s = s.replace("__", "");
    s = s.replace('`', "");
    s = s.replace('#', "");

    // Parentheses → just the content
    s = s.replace('(', "").replace(')', "");

    // = between words → space ("daemon=active" → "daemon active")
    // Process char by char to only replace = between word chars
    let chars: Vec<char> = s.chars().collect();
    let mut result = String::with_capacity(s.len());
    for (i, &ch) in chars.iter().enumerate() {
        if ch == '='
            && i > 0
            && i + 1 < chars.len()
            && chars[i - 1].is_alphanumeric()
            && chars[i + 1].is_alphanumeric()
        {
            result.push(' ');
        } else {
            result.push(ch);
        }
    }
    s = result;

    // N/M → "N of M" (digit/digit patterns)
    let chars: Vec<char> = s.chars().collect();
    let mut result = String::with_capacity(s.len() + 20);
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '/'
            && i > 0
            && i + 1 < chars.len()
            && chars[i - 1].is_ascii_digit()
            && chars[i + 1].is_ascii_digit()
        {
            result.push_str(" of ");
        } else {
            result.push(chars[i]);
        }
        i += 1;
    }
    s = result;

    // "OK" → "okay"
    s = s.replace(" OK ", " okay ");
    s = s.replace(" OK.", " okay.");
    s = s.replace(" OK,", " okay,");
    if s.ends_with(" OK") {
        let len = s.len();
        s.replace_range(len - 2.., "okay");
    }

    // ". " → ", " (sentence breaks → natural pauses)
    s = s.replace(". ", ", ");

    // Collapse whitespace
    let mut prev_space = false;
    let cleaned: String = s
        .chars()
        .filter(|&c| {
            if c == ' ' {
                if prev_space {
                    return false;
                }
                prev_space = true;
            } else {
                prev_space = false;
            }
            true
        })
        .collect();
    s = cleaned;

    // Trim trailing punctuation
    s = s.trim_end_matches(['.', ',', ' ']).to_string();

    s.trim().to_string()
}

/// Maximum characters per chunk for extended message TTS synthesis.
/// ElevenLabs API limit is ~2500 chars; we use 2000 for safety margin.
const MAX_CHUNK_CHARS: usize = 2000;

/// Split text at sentence boundaries (`.!?` followed by whitespace or end-of-string).
/// Each chunk is at most `MAX_CHUNK_CHARS` characters.
/// If a single sentence exceeds the limit, it is split at the character boundary.
pub fn split_into_chunks(text: &str) -> Vec<String> {
    if text.is_empty() {
        return Vec::new();
    }

    if text.len() <= MAX_CHUNK_CHARS {
        return vec![text.to_string()];
    }

    let mut chunks = Vec::new();
    let mut current_chunk = String::new();
    let chars: Vec<char> = text.chars().collect();
    let len = chars.len();
    let mut i = 0;

    while i < len {
        // Find the end of the current sentence
        let mut sentence_end = i;
        while sentence_end < len {
            let ch = chars[sentence_end];
            sentence_end += 1;

            // Check for sentence boundary: `.!?` followed by whitespace or end
            if ch == '.' || ch == '!' || ch == '?' {
                // Look ahead for whitespace or end-of-string
                if sentence_end >= len || chars[sentence_end].is_whitespace() {
                    // Include the trailing whitespace if present
                    if sentence_end < len && chars[sentence_end].is_whitespace() {
                        sentence_end += 1;
                    }
                    break;
                }
            }
        }

        let sentence: String = chars[i..sentence_end].iter().collect();

        // Would adding this sentence exceed the chunk limit?
        if current_chunk.len() + sentence.len() > MAX_CHUNK_CHARS {
            // Flush current chunk if non-empty
            if !current_chunk.is_empty() {
                chunks.push(current_chunk.trim().to_string());
                current_chunk = String::new();
            }

            // If this single sentence exceeds the limit, split it at the character boundary
            if sentence.len() > MAX_CHUNK_CHARS {
                let mut remaining = sentence.as_str();
                while remaining.len() > MAX_CHUNK_CHARS {
                    chunks.push(remaining[..MAX_CHUNK_CHARS].to_string());
                    remaining = &remaining[MAX_CHUNK_CHARS..];
                }
                if !remaining.is_empty() {
                    current_chunk = remaining.to_string();
                }
            } else {
                current_chunk = sentence;
            }
        } else {
            current_chunk.push_str(&sentence);
        }

        i = sentence_end;
    }

    // Flush remaining
    let trimmed = current_chunk.trim().to_string();
    if !trimmed.is_empty() {
        chunks.push(trimmed);
    }

    chunks
}

/// TTS orchestrator that tries ElevenLabs first, falls back to system TTS
pub struct TtsOrchestrator {
    elevenlabs: Option<ElevenLabsClient>,
}

impl TtsOrchestrator {
    /// Create a new TTS orchestrator
    ///
    /// # Arguments
    /// * `elevenlabs` - Optional ElevenLabs client (if API key is available)
    pub fn new(elevenlabs: Option<ElevenLabsClient>) -> Self {
        Self { elevenlabs }
    }

    /// Synthesize text to audio, trying ElevenLabs first and falling back to system TTS
    ///
    /// # Arguments
    /// * `text` - The text to synthesize
    /// * `voice` - Optional voice to use (ElevenLabs voice ID or system voice name)
    ///
    /// # Returns
    /// * `Ok(TtsResult::Audio)` - ElevenLabs audio bytes (MP3 format)
    /// * `Ok(TtsResult::SystemSpoke)` - System TTS handled it (provider name)
    /// * `Err(error_message)` - All TTS methods failed
    ///
    /// # Examples
    /// ```ignore
    /// use claude_daemon::services::receiver::{TtsOrchestrator, TtsResult};
    ///
    /// # async fn example() -> Result<(), String> {
    /// let orchestrator = TtsOrchestrator::new(None);
    /// match orchestrator.synthesize("Hello world", None).await? {
    ///     TtsResult::Audio(bytes) => println!("Got {} bytes of audio", bytes.len()),
    ///     TtsResult::SystemSpoke(provider) => println!("System TTS used: {}", provider),
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub async fn synthesize(&self, text: &str, voice: Option<&str>) -> Result<TtsResult, String> {
        // Normalize dev-speak into natural speech before synthesis
        let text = normalize_for_speech(text);
        let text = text.as_str();

        // Try ElevenLabs if available
        if let Some(ref client) = self.elevenlabs {
            info!("Attempting TTS via ElevenLabs for: {:?}", text);

            let result = if let Some(voice_id) = voice {
                client.synthesize_with_voice(text, voice_id).await
            } else {
                client.synthesize(text).await
            };

            match result {
                Ok(audio_data) => {
                    info!(
                        "ElevenLabs synthesis successful ({} bytes)",
                        audio_data.len()
                    );
                    return Ok(TtsResult::Audio(audio_data));
                }
                Err(e) => {
                    warn!("ElevenLabs failed: {}. Falling back to system TTS", e);
                }
            }
        } else {
            debug!("No ElevenLabs client available, using system TTS");
        }

        // Fallback to system TTS
        info!("Using system TTS for: {:?}", text);
        match SystemTts::speak(text, voice).await {
            Ok(provider) => {
                info!("System TTS successful via {}", provider);
                Ok(TtsResult::SystemSpoke(provider))
            }
            Err(e) => {
                warn!("System TTS failed: {}", e);
                Err(format!("All TTS methods failed. Last error: {}", e))
            }
        }
    }

    /// Check if ElevenLabs is available
    ///
    /// # Returns
    /// * `true` - ElevenLabs client is configured and ready
    /// * `false` - No ElevenLabs client (will fallback to system TTS)
    pub fn has_elevenlabs(&self) -> bool {
        self.elevenlabs.is_some()
    }

    /// Check if any TTS provider is available
    ///
    /// # Returns
    /// * `true` - ElevenLabs or system TTS is available
    /// * `false` - No TTS providers available (synthesize will fail)
    pub async fn is_available(&self) -> bool {
        if self.has_elevenlabs() {
            return true;
        }

        SystemTts::is_available().await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_orchestrator_creation_without_elevenlabs() {
        let orchestrator = TtsOrchestrator::new(None);
        assert!(!orchestrator.has_elevenlabs());
    }

    #[test]
    fn test_normalize_for_speech() {
        // N/M → N of M
        assert_eq!(normalize_for_speech("fleet=10/10"), "fleet 10 of 10");
        assert_eq!(normalize_for_speech("channels=2/5"), "channels 2 of 5");

        // = → space
        assert_eq!(normalize_for_speech("daemon=active"), "daemon active");

        // Parentheses removed
        assert_eq!(
            normalize_for_speech("daemon: OK (restarted)"),
            "daemon: okay restarted"
        );

        // OK → okay
        assert_eq!(normalize_for_speech("fleet OK"), "fleet okay");

        // Markdown stripped
        assert_eq!(normalize_for_speech("**bold** text"), "bold text");

        // Full deploy message
        let input = "Nova deploy: daemon: OK (restarted). fleet: OK (via daemon deploy). dashboard: skip (no changes). health: Nova: daemon=active fleet=10/10 dashboard=running channels=2/5";
        let output = normalize_for_speech(input);
        assert!(!output.contains("="));
        assert!(!output.contains("("));
        assert!(output.contains("10 of 10"));
        assert!(output.contains("2 of 5"));
        assert!(output.contains("okay"));
    }

    #[tokio::test]
    async fn test_orchestrator_is_available() {
        // This test verifies is_available returns a boolean
        // The actual result depends on system TTS installation
        let orchestrator = TtsOrchestrator::new(None);
        let result = orchestrator.is_available().await;
        // Just verify it returns a bool without panicking
        assert!(result || !result);
    }

    #[test]
    fn test_split_empty() {
        assert!(split_into_chunks("").is_empty());
    }

    #[test]
    fn test_split_short_message() {
        let chunks = split_into_chunks("Hello world.");
        assert_eq!(chunks, vec!["Hello world."]);
    }

    #[test]
    fn test_split_multiple_sentences() {
        let text = "First sentence. Second sentence! Third sentence?";
        let chunks = split_into_chunks(text);
        // All fit in one chunk (well under 2000 chars)
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0], text);
    }

    #[test]
    fn test_split_respects_sentence_boundaries() {
        // Build text with sentences that together exceed MAX_CHUNK_CHARS
        let sentence = "A".repeat(600) + ". ";
        let text = sentence.repeat(5); // 5 * ~602 = ~3010 chars
        let chunks = split_into_chunks(&text);
        assert!(chunks.len() >= 2);
        for chunk in &chunks {
            assert!(chunk.len() <= MAX_CHUNK_CHARS + 1); // +1 for possible trailing period
        }
    }

    #[test]
    fn test_split_long_sentence_hard_break() {
        // A single sentence longer than MAX_CHUNK_CHARS with no sentence boundaries
        let text = "A".repeat(MAX_CHUNK_CHARS + 500);
        let chunks = split_into_chunks(&text);
        assert!(chunks.len() >= 2);
        assert_eq!(chunks[0].len(), MAX_CHUNK_CHARS);
    }

    #[tokio::test]
    async fn test_synthesize_fallback_to_system() {
        // This test verifies synthesize can be called and attempts system TTS
        // The actual result depends on system TTS availability
        let orchestrator = TtsOrchestrator::new(None);
        let result = orchestrator.synthesize("test", None).await;

        match result {
            Ok(TtsResult::SystemSpoke(provider)) => {
                assert!(
                    provider == "say"
                        || provider == "espeak-ng"
                        || provider == "espeak"
                        || provider == "festival"
                );
            }
            Err(msg) => {
                assert!(msg.contains("All TTS methods failed"));
            }
            Ok(TtsResult::Audio(_)) => {
                panic!("Should not get ElevenLabs audio without a client");
            }
        }
    }
}
