#!/usr/bin/env bun
/**
 * gen-version.ts — Build-time generator for apps/agent/src/version.gen.ts.
 *
 * Writes two constants — BUILD_SHA (Git short SHA) and BUILT_AT (ISO-8601 UTC) —
 * so the agent's /version endpoint can report what build the binary was compiled
 * from. Invoked as a pre-step before `bun build --compile` (see package.json).
 *
 * Works from any CWD: paths are resolved relative to import.meta.dir.
 *   bun apps/agent/scripts/gen-version.ts          # from repo root
 *   bun scripts/gen-version.ts                     # from apps/agent/
 *
 * Exits non-zero with a clear error to stderr if Git is unavailable or the
 * working tree is not a Git repository.
 */

import { resolve } from "node:path";
import { rename, writeFile } from "node:fs/promises";

const SHA_RE = /^[0-9a-f]{7,40}$/;

// scripts/ → apps/agent/, then src/version.gen.ts
const AGENT_DIR = resolve(import.meta.dir, "..");
const OUT_PATH = resolve(AGENT_DIR, "src", "version.gen.ts");
const TMP_PATH = `${OUT_PATH}.tmp`;

async function getShortSha(): Promise<string> {
  let proc: ReturnType<typeof Bun.spawn>;
  try {
    proc = Bun.spawn(["git", "rev-parse", "--short", "HEAD"], {
      cwd: AGENT_DIR,
      stdout: "pipe",
      stderr: "pipe",
    });
  } catch {
    process.stderr.write(
      "gen-version: not in a Git working tree — required for BUILD_SHA\n",
    );
    process.exit(1);
  }

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);

  if (exitCode !== 0) {
    process.stderr.write(
      "gen-version: not in a Git working tree — required for BUILD_SHA\n",
    );
    if (stderr.trim()) {
      process.stderr.write(`gen-version: git stderr: ${stderr.trim()}\n`);
    }
    process.exit(1);
  }

  const sha = stdout.trim();
  if (!SHA_RE.test(sha)) {
    process.stderr.write(
      `gen-version: unexpected git short-SHA format: ${JSON.stringify(sha)}\n`,
    );
    process.exit(1);
  }
  return sha;
}

async function main(): Promise<void> {
  const sha = await getShortSha();
  const builtAt = new Date().toISOString();

  const content = `// Auto-generated by scripts/gen-version.ts. Do not edit.
export const BUILD_SHA = "${sha}";
export const BUILT_AT = "${builtAt}";
`;

  // Atomic write: tmp + rename — parallel readers never see a torn file.
  await writeFile(TMP_PATH, content, "utf8");
  await rename(TMP_PATH, OUT_PATH);

  process.stdout.write(`gen-version: BUILD_SHA=${sha} BUILT_AT=${builtAt}\n`);
}

await main();
